global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'auth-service'
    static_configs:
      - targets: ['auth-service:8000']
    metrics_path: /metrics

  - job_name: 'did-service'
    static_configs:
      - targets: ['did-service:8000']
    metrics_path: /metrics

  - job_name: 'credential-service'
    static_configs:
      - targets: ['credential-service:8000']
    metrics_path: /metrics

  - job_name: 'verification-service'
    static_configs:
      - targets: ['verification-service:8000']
    metrics_path: /metrics