global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'auth-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['auth-service:8000']

  - job_name: 'did-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['did-service:8000']

  - job_name: 'credential-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['credential-service:8000']

  - job_name: 'verification-service'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['verification-service:8000']